sonar.projectKey=MySecureWebApp
sonar.projectName=MySecureWebApp

sonar.sources=app,tests
sonar.exclusions=node_modules/**,common-passwords.txt,reports/**,odc-reports/**,odc-data/**,gitea/**,mysql_data/**,certbot/**

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
